---
# .. seealso:: `ansible-doc junos_command`
- name: >-
    Run command '{{ rntebr_command }}' and get results
  junos_command:
    commands: "{{ rntebr_command }}"
    display: "{{ junos_command.display | d('xml') }}"
    interval: "{{ junos_command.interval | d(1) }}"
    match: "{{ junos_command.match | d('all') }}"
    retries: "{{ junos_command.retries | d(10) }}"
    wait_for: "{{ junos_command.wait_for | d([]) }}"
  ignore_errors: "{{ rntebr_ignore_errors | d(false) }}"
  register: rntebr_res

# vim:sw=2:ts=2:et:
